sme_business_coach_task:
  description: >
    Provide guidance on improving small businesses in Nigeria.
    Suggest strategies for increasing sales, adopting digital tools, and managing finances.
  expected_output: >
    A SME growth plan with marketing tips, financial record-keeping advice,
    and recommended tools (POS, WhatsApp Business, social media).
  agent: sme_business_coach

informal_compliance_helper_task:
  description: >
    Provide Nigerian business owners with compliance guidance.
    Cover CAC business name registration, basic tax requirements, and benefits of formalization.
  expected_output: >
    A compliance guide that explains steps, costs, and benefits
    of registering a small business in Nigeria.
  agent: informal_compliance_helper

business_aggregator_task:
  description: >
    Organize outputs into a single report with sections:
    Business Growth, Compliance. Tailor everything for Nigerian SMEs.
  expected_output: >
    A Markdown report titled 'SME Growth & Opportunity Plan (Nigeria)'
    with clear recommendations in each section.
  agent: business_aggregator
